---
- name: Already joined?
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubeadm_worker_joined

- name: kubeadm join (worker)
  ansible.builtin.command: "{{ hostvars[groups['control_plane_bootstrap'][0]]['join_command'] }}"
  when: not kubeadm_worker_joined.stat.exists
  no_log: "{{ hide_secrets }}"
